# .travis.yml

# Use Ubuntu 20.04 LTS as the build environment
os: linux
dist: focal

# Install dependencies
install:
  - echo "Installing dependencies here"

# Run tests
script:
  - echo "Run tests here"

# Deploy script
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
