# .travis.yml

# Use Ubuntu 20.04 LTS as the build environment
#os: linux
#dist: focal
language: minimal

branches:
  only:
    - master
# Install dependencies
install:
  - echo "Installing dependencies here"

# Run tests
script:
  - echo "Run tests here"

# Deploy script
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash deploy.sh
  on:
    branch: master
